### ISSUE TITLE
EnrichmentMap: download links for input files don't work

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/guide#39]
> RNA-Seq to EnrichmentMap guide. The download links for the enrichment map input files don't work. They all download some html file and not the actual data files.

> https://www.pathwaycommons.org/guide/workflows/rna_seq_to_enrichment_map/visualize/

**Comment by princyym** [comment]
Hello, I am Princy, reviewing your issue. I have checked this website and I found that the files you are talking about is downloading really well and if I am not able to understand, Kindly, correct me and explain me the root cause so that I can work upon it and take a step ahead in this journey, as a beginner contributor.
And I really thing to change the UI of this website as when in the desktop type device, it not fit in properly. Additionally, the font of the references should be the minimized, so the main content gains its importance.

Regards
Princy mangla
